Xmen.UI/Pages/Contact/Contact.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;

namespace Xmen.UI.Pages.Contact
{

    /// <summary>
    /// Login Form (input fields => username, password)
    /// Use Tag-Helpers to bind to the code-behind property
    /// Feedback property is shown to the user if ModelState.IsValid == true
    /// Check if Input from user is valid.
    /// </summary>
    
    public class ContactModel : PageModel
    {
        //Check this out => https://docs.microsoft.com/en-us/aspnet/core/mvc/views/working-with-forms?view=aspnetcore-5.0

        /// <summary>
        /// Model Binding is the process in which incoming data is mapped to C# Objects
        /// </summary>

        [BindProperty]
        [EmailAddress]
        [Required]
        public string Email { get; set; }
        public string Feedback { get; set; }


        /// <summary>
        /// Forms are created mainly to collect data from the user.
        /// In the case of Razor Pages, form data is submitted to the "page model" for processing
        /// The page model uses a process called "model binding" to map the incoming data to C# Objects
        /// This allows us to decide whether the data we are working is valid.
        /// Validation is necessary to be able to trigger the proper response for the end user as well as
        /// storing the right type of data.
        /// Apart from OnGet there are other methods which are named following the HTTP methods naming conventions
        /// id est OnGet, OnPost, OnDelete, OnPut 
        /// By using specific tag-helpers we can configure specific methods to handle any sort of request
        /// This allows us to break Razor Pages conventions
        /// </summary>
        /// 
        public ContactModel()
        {

        }
        /// <summary>
        /// The OnGet method is triggered when the browser requests the page to load.
        /// </summary>
        public void OnGet()
        {

        }
        /// <summary>
        /// OnPost is recognized by Razor pages as a form submission handler that 
        /// can be used to map incoming data in our "Page Model"
        /// OnPost handles the data submitted by the User. Proper asp tag helpers are used
        /// in conjunction with these razor specific methods.
        /// 
        /// When Posting Data, Razor Pages will try to convert form input to the FormData C# 
        /// object we've described above.
        /// </summary>
        public void OnPost()
        {

        }
        public void OnPostSubscribe()
        {
            if (ModelState.IsValid)
            {
                Feedback = "You Have Subscribed!";
            }
        }
    }
}

Xmen.UI/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Xmen.UI.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Xmen.UI/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Xmen.UI.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Xmen.UI/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Xmen.UI.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Xmen.UI/Pages/Contact/Contact.cshtml
@page
@model Xmen.UI.Pages.Contact.ContactModel
@{
}

<h1>Newsletter</h1>
<div class="container">
    @if (!string.IsNullOrEmpty(Model.Feedback))
    {
        <div class="alert alert-success">
            <p>@Model.Feedback</p>
        </div>
    }
    <form asp-page-handler="Subscribe">
        <div class="form-group">
            <label asp-for="Email">Email address:</label>
            <input asp-for="Email" class="form-control" id="">
            <span asp-validation-for="Email" class="alert alert-success" role="alert"></span>
            <button type="submit">Subscribe</button>
        </div>
    </form>

</div>

Xmen.UI/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Xmen.UI/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Xmen.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Xmen.UI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Contact/Contact">Contact</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Xmen.UI - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>